name: CI

on:
  push:
    branches: [ dev, feature/**, main ]   # Run on pushes
  pull_request:
    branches: [ dev ]                     # Run on PRs into dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, javascript]    # Run once for Python, once for JS

    steps:
      # 1) Pull code
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Backend (Python) ----------
      - name: Detect backend folder
        id: detect_backend
        if: matrix.language == 'python'
        run: |
          if [ -d "backend" ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Python
        if: matrix.language == 'python' && steps.detect_backend.outputs.present == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'                     # Cache pip installs
          cache-dependency-path: |
            backend/requirements*.txt
            backend/pyproject.toml

      - name: Install Python dev tools
        if: matrix.language == 'python' && steps.detect_backend.outputs.present == 'true'
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install ruff isort pytest

      - name: Python lint (ruff + isort)
        if: matrix.language == 'python' && steps.detect_backend.outputs.present == 'true'
        working-directory: backend
        run: |
          ruff check .
          isort --check-only .

      - name: Python tests (pytest)
        if: matrix.language == 'python' && steps.detect_backend.outputs.present == 'true'
        working-directory: backend
        run: |
          pytest -q

      # ---------- Frontend (JavaScript/TypeScript) ----------
      - name: Detect frontend folder
        id: detect_frontend
        if: matrix.language == 'javascript'
        run: |
          if [ -d "frontend" ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Node.js
        if: matrix.language == 'javascript' && steps.detect_frontend.outputs.present == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            frontend/package.json

      - name: Install Node deps
        if: matrix.language == 'javascript' && steps.detect_frontend.outputs.present == 'true'
        working-directory: frontend
        run: npm ci

      - name: JS lint (ESLint + Prettier)
        if: matrix.language == 'javascript' && steps.detect_frontend.outputs.present == 'true'
        working-directory: frontend
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx
          npx prettier --check .

      - name: Frontend tests (Vitest)
        if: matrix.language == 'javascript' && steps.detect_frontend.outputs.present == 'true'
        working-directory: frontend
        run: |
          npx vitest run --reporter=dot --passWithNoTests
